# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: GenWhisperMsg.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'GenWhisperMsg.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13GenWhisperMsg.proto\"\x85\x06\n\nGenWhisper\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12!\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x13.GenWhisper.Nested2\x1a\xc5\x05\n\x07Nested2\x12\x0b\n\x03uid\x18\x01 \x01(\x04\x12\x0f\n\x07\x63hat_id\x18\x02 \x01(\x04\x12\x11\n\tchat_type\x18\x03 \x01(\x05\x12\x0b\n\x03msg\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x12+\n\x06\x66ield9\x18\t \x01(\x0b\x32\x1b.GenWhisper.Nested2.Nested9\x12\x10\n\x08language\x18\n \x01(\t\x12-\n\x07\x66ield13\x18\r \x01(\x0b\x32\x1c.GenWhisper.Nested2.Nested13\x12\x31\n\x0b\x65mpty_field\x18\x0e \x01(\x0b\x32\x1c.GenWhisper.Nested2.Nested14\x12\x11\n\tCelebrity\x18\x10 \x01(\x04\x1a\n\n\x08Nested14\x1a\xff\x01\n\x07Nested9\x12\x10\n\x08Nickname\x18\x01 \x01(\t\x12\x11\n\tavatar_id\x18\x02 \x01(\x03\x12\x11\n\tbanner_id\x18\x03 \x01(\x03\x12\x0c\n\x04rank\x18\x04 \x01(\x05\x12\r\n\x05\x62\x61\x64ge\x18\x05 \x01(\x05\x12\x11\n\tClan_Name\x18\x08 \x01(\t\x12\x0f\n\x07\x66ield10\x18\n \x01(\x05\x12\x17\n\x0fglobal_rank_pos\x18\x0b \x01(\x05\x12\x30\n\x07\x66ield13\x18\r \x01(\x0b\x32\x1f.GenWhisper.Nested2.NestedBadge\x12\x30\n\x07\x66ield14\x18\x0e \x01(\x0b\x32\x1f.GenWhisper.Nested2.NestedPrime\x1a\x1c\n\x0bNestedBadge\x12\r\n\x05value\x18\x01 \x01(\x05\x1aH\n\x0bNestedPrime\x12\x11\n\tprime_uid\x18\x01 \x01(\x05\x12\x13\n\x0bprime_level\x18\x02 \x01(\x05\x12\x11\n\tprime_hex\x18\x03 \x01(\t\x1a?\n\x08Nested13\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x10\n\x08url_type\x18\x02 \x01(\x05\x12\x14\n\x0curl_platform\x18\x03 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GenWhisperMsg_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENWHISPER']._serialized_start=24
  _globals['_GENWHISPER']._serialized_end=797
  _globals['_GENWHISPER_NESTED2']._serialized_start=88
  _globals['_GENWHISPER_NESTED2']._serialized_end=797
  _globals['_GENWHISPER_NESTED2_NESTED14']._serialized_start=360
  _globals['_GENWHISPER_NESTED2_NESTED14']._serialized_end=370
  _globals['_GENWHISPER_NESTED2_NESTED9']._serialized_start=373
  _globals['_GENWHISPER_NESTED2_NESTED9']._serialized_end=628
  _globals['_GENWHISPER_NESTED2_NESTEDBADGE']._serialized_start=630
  _globals['_GENWHISPER_NESTED2_NESTEDBADGE']._serialized_end=658
  _globals['_GENWHISPER_NESTED2_NESTEDPRIME']._serialized_start=660
  _globals['_GENWHISPER_NESTED2_NESTEDPRIME']._serialized_end=732
  _globals['_GENWHISPER_NESTED2_NESTED13']._serialized_start=734
  _globals['_GENWHISPER_NESTED2_NESTED13']._serialized_end=797
# @@protoc_insertion_point(module_scope)
